### ISSUE TITLE
Error with docker build

### ISSUE THREAD

**Issue by gboege** [FIWARE-GEs/processing.Perseo.Back-End#1]
Hi

When building the image with "docker build -t perseo ." the process fails and exits.

Here the last and relevant part of the error log:

Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.17/surefire-api-2.17.jar (144 KB at 83.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar (309 KB at 172.5 KB/sec)
[INFO] Surefire report directory: /code/target/surefire-reports
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.pom (3 KB at 22.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.17/surefire-providers-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.17/surefire-providers-2.17.pom (3 KB at 25.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar (63 KB at 390.1 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.367 s
[INFO] Finished at: 2018-11-10T15:54:09+00:00
[INFO] Final Memory: 26M/194M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project perseo-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /code && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /code/target/surefire/surefirebooter6326315880551862738.jar /code/target/surefire/surefire6398250085628932715tmp /code/target/surefire/surefire_03466262916763989654tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command '/bin/sh -c apt-get update &&     apt-get install -y maven openjdk-8-jdk &&     mvn dependency:resolve &&     mvn verify &&     mvn package &&     rm -rf /usr/local/tomcat/webapps/* &&     cp target/perseo-core-*.war /usr/local/tomcat/webapps/perseo-core.war &&     mvn clean &&     apt-get remove -y openjdk-8-jdk &&     apt-get clean &&     apt-get remove -y maven &&     apt-get -y autoremove &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /code/src' returned a non-zero code: 1

**Comment by caa06d9c** [comment]
Hi! Please, open ISSUE at original repository: 
https://github.com/telefonicaid/perseo-core
